name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloudinary_public: ^0.23.1
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  intl: ^0.17.0
  lottie: ^3.1.0
  provider: ^6.1.2
  charts_flutter: ^0.12.0
  flutter_product_card: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
    - assets/icons/
    - assets/images/
    - ./.env
